# Generated by Django 3.0.8 on 2020-07-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('name', 'email')},
        ),
    ]
