# Generated by Django 3.0.8 on 2020-08-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('name', 'email')},
        ),
    ]
